= Flamingo Big Data Platform: 사용자 라이센스 동의서(EULA)
Cloudine, Inc.
v2.0.0, 2015-07-08:

== 대상 범위

본 Flamingo의 사용자 라이센스 동의서는 Flamingo 0.x~Flamingo 2.x까지 모든 버전을 대상으로 적용합니다.

== 사용과 관련하여 중요한 정리 사항

=== 금지된 사용

* GPL v3 라이센스가 아닌 상업적 판매를 목적으로 한 제품에서 Flamingo를 포함시켜 판매할 수 없습니다(Flamingo OEM 라이센스가 적용됩니다).
* Flamingo의 소스코드를 포함하는 경우 다른 제품명칭을 사용할 수 없습니다(Flamingo OEM 라이센스가 적용됩니다).
* Flamingo에 포함되어 있는 에이전트와 라이센스 관리 코드는 Decompiler 등으로 decompile할 수 없습니다.
* 정해진 라이센스를 타 용도로 사용할 수 없습니다(예; 아카데미 또는 Trial을 상업적으로 이용하는 경우).
* 라이센스 파일에 기술된 노드수 및 사용자수를 초과하여 노드와 사용자를 사용할 수 없습니다.

[NOTE]
상업적 이용이라고 함은 제품 공급(제품공급 확약서가 없더라도 공급의 의미를 가지면 공급이라고 판단합니다) 및 기술지원을 받는 등의 상업적인 일체의 활용을 의미합니다.

=== 전용 사용

* 상업적 이용을 위해서 Flamingo를 설치하는 서버는 반드시 Commercial License를 취득해야 합니다.
* Flamingo를 설치한 서버를 변경하거나 교체하는 경우 Cloudine, Inc로 부터 Commercial License를 재발급 받아야 합니다(신규로 구매해야 하는 것은 아닙니다).

=== 컨설턴트 및 SI 사업자

* SI 및 컨설턴트가 공공 및 민간 프로젝트에서 Flamingo의 기능을 확장하기 위해서 Workflow Designer에 모듈을 추가거나 제공 기능을 수정하는 경우 Commercial License(OEM, Subscription) 구매시 자유롭게 가능합니다.

=== GPL & Trial Development

* Trial License를 발급한 시점에서 만료되는 시점까지 사용은 허가하나, 수정은 허가하지 않습니다.
* Commercial License에서 GPL v3 라이센스로 변경은 허가하지 않습니다.

== 라이센스 조항

[WARNING]
주의 깊게 읽으시기 바랍니다. 본 최종사용자 라이센스 계약(이 "EULA")에는 사용자의 소프트웨어(아래에서 정의됨)
사용에 적용되는 약관 및 조건이 포함되어 있으며, 사용자의 권리에 대해 중요한 제한이 명시되어 있습니다.
사용자는 본 EULA를 주의 깊게 읽고, 귀중한 재산으로 취급해야 합니다.

=== 본 EULA에 대해서

본 EULA는 이 EULA와 함께 동봉되었거나 본 EULA를 수반하고 있는 Cloudine, Inc(이하 "Cloudine")
소프트웨어 제품(들)(개별적 및 집합적으로 "소프트웨어")에 대한 사용자의 사용에 적용됩니다.
"소프트웨어"라는 용어에는 Cloudine이 규정하는 범위까지, 다음 사항이 포함됩니다.
1) 소프트웨어에 대한 개정판, 업데이트 및/또는 업그레이드,
2) 관행적으로 컴퓨터 소프트웨어 제품과 함께 사용되거나 배포되는 데이터, 이미지 또는 실행 파일, 데이터베이스, 데이터 엔진, 컴퓨터 소프트웨어 또는 이와 유사한 품목,
3) 해당 소프트웨어와 함께, 또는 결합해서 사용하고자 의도된 모든 형태의 것, 그리고
4) 연관된 미디어, 문서자료(실제적, 전자적 및 온라인 자료 포함) 및 인쇄된 자료("문서자료").

소프트웨어의 일부로서 제공되는 Flamingo를 사용할 경우, 본 라이센스가 사용자에게 Flamingo에 포함되어 있는 Sencha ExtJS를 분리히ㅏ여 사용할 수 있는 어떠한 권리도 부여하지 않는다는 점을 유의하시기 바랍니다.

본 EULA는 사용자와 Cloudine 간에 법적 구속력이 있는 계약입니다. 사용자는 사용자의 고용주를 위해 활동하는 임원 또는 그 밖의 직원과 같이, 회사 또는 그 밖의 법인체 담당자로서 활동하고 있는 경우, "사용자" 및 "사용자의"라는 용어는 사용자가 활동하고 있는 본인, 권리 주체 또는 그 밖의 법인체를 의미합니다.
그러나 사용자가 타인의 한 담당자로서 활동하는 경우일 때에도, 사용자는 여전히 저작권 침해와 같은 대한민국 법률 위반에 대해서 개인적으로 책임을 지게 될 수 있다는 점에 유의하시기 바랍니다.

사용자가 본 EULA의 약관을 수락한다고 표명함으로써, 사용자는 Cloudine과 사용자가 실제로 이 EULA에 서명한 것과 동일한 범위까지 법적으로 본 EULA의 구속력이 발휘되도록 의도한 것이며,
본 EULA에 의해 법적 구속력이 발휘됩니다. 소프트웨어를 설치, 복사 또는 그 밖의 방법으로 사용함으로써, 사용자는 이 EULA의 모든 계약조건에 법적 구속력이 발휘되는 것에 동의합니다.
사용자가 해당 약관 및 조건 전부에 동의하지 않는 경우, 소프트웨어를 설치하거나 사용해서는 안 됩니다.
사용자가 이 EULA의 약관 중 어느 것에든 동의하지 않고, 여하한 사유로든 설치가 시작되거나 완료되었다면, 사용자는 상황에 따라 소프트웨어 설치를 취소하거나 설치된 소프트웨어를 삭제해야 합니다.
아울러, 사용자는 사용자가 소프트웨어를 취득한 업체의 반품정책에 따라서 해당 소프트웨어를 즉시 해당 업체에 반품해야 합니다.
반품정책은 리셀러 간에 차이가 있을 수 있으므로, 사용자는 구매 시점에 사용자가 동의한 공급업체의 반품정책을 준수해야 합니다.

=== 사용자 라이센스

아래에서 더욱 자세히 제공되는 바와 같이, 본 EULA는 2가지 라이선스, 즉 1) 연단위 갱신을 통한 기술지원을 동반한 Subscription 라이센스와 2) OEM 라이센스를 사용자에게 부여합니다.
본 라이선스(아래에 기술된 소스 코드 라이선스를 포함하며, 개별적 및 집합적으로 "라이선스"라 칭함)는 아래에 더욱 자세히 설명되고 규정되어 있습니다.

==== Subscription 라이센스

사용자는 이로써 사용자가 본 EULA의 모든 약관 및 조건을 완전히 준수하는 것에 한해, 명시적인 조건으로, 데이터 처리, 분석, 시각화를 하기 위해 소프트웨어를 사용할 수 있는 제한적이고 로열티-무료인 비독점적 권리를 부여받습니다.

http://www.componentone.co.kr/support/eula.htm

==== OEM 라이센스

사용자는 이로써 사용자가 본 EULA의 모든 약관 및 조건을 완전히 준수하는 것에 한해, 명시적인 조건으로, 개발된 소프트웨어를 설계, 개발 및 테스트하기 위해 소프트웨어를 사용할 수 있는 제한적이고 로열티-무료인 비독점적 권리를 부여받습니다.

=== 소스코드 라이센스

Cloudine은 GPL v3 라이센스에 따라서 Flamingo의 바이너리와 함께 소스코드를 함께 제공합니다.

==== 사용자의 소스코드 라이센스

Cloudine은 GPL v3 라이센스에 따라서 Flamingo의 바이너리와 함께 소스코드를 함께 제공하지만 에이전트와 라이센스 관리는 소스코드 제공에서 제외됩니다.
사용자는 GPL v3 라이센스에 따라서 오픈소스 버전을 사용할 수 있으나 수정시 사용시 GPL v3 라이센스를 따라야 합니다.
Cloudine은 GPL v3 라이센스에 따라서 배포된 라이센스를 커뮤니티 라이센스라 정하며 커뮤니티 라이센스에 속한 Flamingo의 소스코드 포함된 경우 상업적 이용(Flamingo의 바이너리 및 소스코드를 통해 판매 등의 이익을 취하는 행위)을 금지합니다.

=== 지적 재산

Cloudine은 GPL v3 라이센스에 따라서 Flamingo의 바이너리와 함께 소스코드를 함께 제공합니다.

==== 저작권

사용자는 Cloudine이 소프트웨어에 통합된 제3자의 특정 기술의 정당한 라이센스 보유자 권한에 해당하는 제한적인 범위까지를 제외하고는,
소프트웨어(소프트웨어에 통합된 모든 이미지, 사진, 애니메이션, 동영상, 오디오, 음악, 텍스트 및 "애플릿"을 포함하나 이에 국한되지 않음),
본 소프트웨어의 어떠한 복사본, 그리고 이에 대한 또는 이와 관련된 어떠한 저작권 및 기타 지적 재산권이라도 모두 Cloudine이 배타적으로 소유하고 있다는 것에 동의합니다.
본 소프트웨어는 저작권 법률과 국제 조약의 규정에 의해서 보호받습니다. 본 소프트웨어는 사용자에게 라이센스가 허가된 것이지, 사용자에게 매각된 것이 아닙니다.
Cloudine는 본 EULA에서 사용자에게 명시적이고 구체적으로 부여한 권리 이외의 모든 권리를 보유합니다.

==== 백업

사용자는 전적으로 백업이나 기록보관의 목적으로만 소프트웨어의 복사본을 만들 수 있습니다.

==== 일반 제한 사항

사용자는 이 조항에 따른 제한에도 불구하고 관련 법률에서 해당 행위를 명시적으로 허용하는 범위까지만을 제외하고는,
본 소프트웨어의 에이전트 및 라이센스 관리 등의 구성 요소에 대한 역엔지니어링, 디컴파일 또는 디스어셈블해서는 안 됩니다.

==== 소프트웨어 양도

사용자는 소프트웨어를 대여하거나 임대해서는 안 됩니다. 사용자는 사용자가 사본을 보유하지 않고, 모든 소프트웨어(모든 구성 요소 부분, 미디어와 인쇄된 자료, 업데이트, 업그레이드, 본 EULA, 그리고 해당하는 경우에는 인증서 포함)를
양도하며, 양수인이 본 EULA의 약관 및 조건에 의해 법적인 구속력에 귀속되는 것에 동의할 것을 전제하는 경우, 본 EULA에 따른 사용자의 권리 전부를 영구적으로 양도할 수 있습니다.
소프트웨어가 업데이트 또는 업그레이드 버전인 경우, 양도에는 반드시 본 소프트웨어의 모든 이전 버전이 포함되어야 합니다.

==== 계약 종료

사용자가 본 EULA에 포함된 약관 및 조건을 준수하지 못하는 경우, Cloudine은 자신이 갖는 다른 어떤 권리도 침해하지 않고 본 EULA와 라이센스를 종료할 수 있습니다.
그러한 경우, 사용자는 반드시 에이전트와 라이센스 관리 구성 요소 부분 전부를 파기해야 합니다.

=== 보증 및 구제수단

==== 제한적 보증

Cloudine은, 해당하는 경우, 원본 미디어가 본 소프트웨어의 인도일로부터 30일 동안 하자가 없고, 본 소프트웨어가 실질적으로 소프트웨어의 문서자료에 설명된 대로 작동할 것임을 보증합니다. Cloudine은 아울러 다음 사항을 보증합니다.
(i) Cloudine은 본 계약을 체결하고 본 계약에 기재된 라이센스 권리를 부여할 수 있는 완전한 권한을 가지고 있습니다.
(ii) Cloudine은 소프트웨어에 대해 본 계약에서 사용자에게 부여된 권리와 부합되지 않는 어떠한 권리도 제3자에게 부여하지 않았으며, 앞으로도 부여하지 않을 것입니다. 그리고,
(iii) 소프트웨어는 제3자가 보유한 영업비밀, 저작권, 상표 또는 그 밖의 사적 권리를 침해하지 않고, 앞으로도 침해하지 않을 것이며, 제3자가 보유한 특허를 침해하지도 않습니다.
바로 앞 문장에서 규정된 보증사항을 제외하고, Cloudine은 Cloudine이 제공하는 소프트웨어, 문서자료 및 그 밖의 것에 대해서 관련 법률상 허용되는 최대한의 범위까지 일체의 보증을 명시적으로 부인하며,
Cloudine은 상업성이나 특정 목적을 위한 적합성에 대한 묵시적 보증을 포함하되 이에 국한되지 않고, 명시적이든, 묵시적이든, 어떠한 종류의 보증도 없이 "있는 그대로" 제공됩니다.
소프트웨어와 문서자료의 사용이나 성능으로부터 발생하는 모든 위험은 사용자가 부담합니다. 본 제한적 보증은 사용자에게 분명한 법적 권리를 부여합니다. 사용자는 국가마다 다른 그 밖의 권리를 가질 수도 있습니다.

Cloudine은 이 계약과 함께 라이센스가 부여되는 소프트웨어가 오로지 Cloudine이 기술 지원을 제공하는 개발 환경인 Apache Hadoop 환경에서 그 문서자료에 따라 구동하고 작동하기 위한 용도라는 점을 진술합니다.
위와 같은 진술에도 불구하고, 소프트웨어가 독립형 소프트웨어 라이브러리로서든 컨트롤이나 애플리케이션에 포함된 구성 요소로서든 다른 컨테이너나 개발 환경에서 해당 소프트웨어의 문서자료와 일관되게 실행 및 작동될 수 있지만,
Cloudine은 그러한 내용을 명시적으로 진술하지 않습니다. Apache Tomcat, Sencha ExtJS 이외의 개발 환경, 애플리케이션 및/또는 컨테이너는 다른 라이센스 약관이 적용될 수 있는 비표준 컨테이너로 간주합니다.
그러한 라이센스 약관은 본 EULA에 포함되어 있지 않으며, 직접 Cloudine에 연락하여 취득할 수 있습니다.

소프트웨어가 소프트웨어의 문서자료에 설명된 바와 같이 실질적으로 수행되지 못한 것이 사고 또는 소프트웨어의 오용 또는 잘못된 적용으로 인한 경우, 본 제한적 보증은 효력이 없고 무력화됩니다.

==== 제한적 구제수단

Cloudine은 샘플 애플리케이션 코드, 재배포가능 파일, 소프트웨어의 평가판 버전과 재판매용 및 OEM 버전이 아닌 경우에 대해서,
명시적이든 묵시적이든 어떠한 구제수단이나 보증도 제공하지 않습니다. 샘플 애플리케이션 코드 및 소프트웨어의 평가판 버전과 재판매용 및 OEM이 아닌 버전은 "있는 그대로" 제공됩니다.

본 EULA에 따른 Cloudine의 모든 책임과 사용자의 유일한 구제수단은 전적으로 Cloudine의 선택에 따라,
(a) 본 소프트웨어에 지급된 대금을 환불하거나,
(b) Cloudine의 재량으로 온라인이나 그 밖의 방법으로 배포되는 업데이트를 통해 소프트웨어를 수정하거나, 또는
(c) 실질적으로 소프트웨어 문서자료에 설명된 대로 수행되는 소프트웨어로 문제가 있는 소프트웨어를 교체하는 것 중 하나입니다.
단, 이는 사용자가 본 EULA를 수락하지 않는 경우의 소프트웨어 반품에 대해서는 앞서 규정된 것과 동일한 방법으로 해당 소프트웨어를 반환하는 경우에 한합니다.
수리되거나 교체된 소프트웨어의 미디어에 대해서는 원래 보증기간의 잔여기간이나 30일 중 더 장기에 해당하는 기간에 대해 보증합니다.
이러한 구제수단은 대한민국 외부에서는 제공되지 않습니다. 관련 법률상 허용되는 최대한의 범위까지, Cloudine은 어떠한 상황에서도 소프트웨어의 사용 또는 사용 불가능으로부터 발생하는
어떠한 손해(사업상의 수익, 사업 방해, 사업 정보 손실 또는 그 밖의 금전적 손실에 대한 손해를 포함하되 이에 국한되지 않음)에 대해서도 책임을 지지 않으며,
이는 Cloudine이 해당 손해의 발생 가능성에 대해 고지받은 경우에서도 마찬가지입니다. 일부 국가/관할지역에서는 특정한 경우, 결과적 또는 부차적 손해에 대한 책임의 배제 또는 제한을 허용하지 않으므로,
위 제한 사항이 사용자에게 적용되지 않을 수도 있습니다.

=== 기타 사항

이는 전체 계약서입니다. 본 EULA(소프트웨어와 함께 제공되는 본 EULA의 모든 부록 포함)는 본 소프트웨어와 관련하여 사용자와 Cloudine 사이에 합의한 내용 전부에 대해 최종적이고 완성된 것이며 유일한 진술입니다.
본 EULA는 구두 또는 서면을 불문하고 본 EULA의 주제와 관련하여 이전에 이루어졌거나 본 EULA와 동시에 이루어진 모든 제안, 구매 주문, 광고 및 그 밖의 모든 커뮤니케이션에 대해 우선합니다.
여기에 포함된 사항 이외의 모든 약관 또는 조건과 이 약관 및 조건을 어떤 방식으로든 변경하는 다른 양해사항이나 합의사항은 당사자 간에 서면으로 체결하거나 당사자들이 객관적이고 확정적으로 어떠한 방법으로든
법적 구속력에 귀속되기로 하는 구두 이외의 방식(소프트웨어 설치를 계속하는 행위 등)으로 이루어진 합의에 의하지 않는 한, 당사자에 대한 법적 구속력이 없습니다.
Cloudine의 직원, 대리인 및 그 밖의 담당자에게는 본 EULA를 구두로 변경할 수 있는 권한이 없습니다.

사용자는 Cloudine에 배상합니다. 사용자는 변호사 보수를 포함하여, 사용자의 개발된 소프트웨어, 사용자의 개발된 웹 서버 소프트웨어, 또는 본 EULA의 약관 및 조건에 대한
사용자의 어떠한 위반으로부터 발생하거나 그로 인해 초래된 일체의 청구 또는 소송에 대해 Cloudine과 Cloudine의 공급자 및 리셀러에 배상하고, 피해가 없도록 하며, 이들을 방어해야 합니다.

본 EULA의 해석. 어떠한 사유로든 권한 있는 사법권에서 본 EULA의 조항이나 그 일부를 집행 불가능하다고 판정하는 경우,
본 EULA의 해당 조항은 당사자들의 의도에 부합될 수 있도록 가능한 최대한의 범위까지 적용해야 하며, 본 EULA의 나머지 부분은 완전한 효력을 지속합니다.
정의된 용어에서 파생된 용어는 정의된 그 용어와 동일한 의미를 갖습니다. 당사자 중 한쪽이 본 EULA의 어느 조항에 대한 이행을 강제하지 못하더라도
해당 조항이나 다른 어떠한 조항에 대해서도 앞으로의 이행 강제에 대한 권리를 포기한 것으로 간주해서는 안 됩니다. 법률에 따라 달리 요구되거나 우선한 경우를 제외하고,
본 EULA는 법률저촉 원칙과 상관없이 대한민국 법률의 지배를 받습니다.
본 소프트웨어를 대한민국 외부에서 취득한 경우, 현지 법률이 적용될 수 있습니다. 하지만 국제물품매매계약에 관한 국제연합 협약의 적용은 명시적으로 배제됩니다.
본 EULA의 원본은 한글로 작성되었습니다. 본 EULA의 한글본과 다른 언어본 사이에 발생할 수 있는 차이나 상충은 한글본을 참조해서 해결하고 해석해야 하며, 한글본이 항상 우선합니다.
